const songs = [
    "Planet Claire",
    "52 Girls",
    "Dance This Mess Around",
    "Rock Lobster",
    "Lava",
    "There's a Moon in the Sky (Called the Moon)",
    "Hero Worship",
    "6060-842",
    "Downtown",
    "Party Out of Bounds",
    "Dirty Back Road",
    "Runnin' Around",
    "Give Me Back My Man",
    "Private Idaho",
    "Devil in My Car",
    "Quiche Lorraine",
    "Strobe Light",
    "53 Miles West of Venus",
    "Loveland",
    "Deep Sleep",
    "Mesopotamia",
    "Cake",
    "Throw That Beat in the Garbage Can",
    "Nip It in the Bud",
    "Legal Tender",
    "Whammy Kiss",
    "Song for a Future Generation",
    "Butterbean",
    "Trism",
    "Queen of Las Vegas",
    "Don't Worry",
    "Moon 83",
    "Big Bird",
    "Work That Skirt",
    "Summer of Love",
    "Girl from Ipanema Goes to Greenland",
    "Housework",
    "Detour Thru Your Mind",
    "Wig",
    "Theme for a Nude Beach",
    "Ain't It a Shame",
    "Juicy Jungle",
    "Communicate",
    "She Brakes for Rainbows",
    "Cosmic Thing",
    "Dry County",
    "Deadbeat Club",
    "Love Shack",
    "Junebug",
    "Roam",
    "Bushfire",
    "Channel Z",
    "Topaz",
    "Follow Your Bliss",
    "Tell It Like It T-I-Is",
    "Hot Pants Explosion",
    "Good Stuff",
    "Revolution Earth",
    "Dreamland",
    "Is That You Mo-Dean?",
    "The World's Green Laughter",
    "Vision of a Kiss",
    "Breezin'",
    "Bad Influence",
    "Debbie",
    "Hallucinating Pluto",
    "Pump",
    "Hot Corner",
    "Ultraviolet",
    "Juliet of the Spirits",
    "Funplex",
    "Eyes Wide Open",
    "Love in the Year 3000",
    "Deviant Ingredient",
    "Too Much to Think About",
    "Dancing Now",
    "Keep This Party Going"
];

const lyrics = [
    "She came from Planet Claire",
    "It wasn't a rock",
    "Watch out for that piranha",
    "Reckless drivin', like a sports car",
    "Get out of the state you're in",
    "I'll give you fish",
    "Ew, house-a-tosis",
    "I'll meet you by the third pyramid",
    "According to my recipe, you put it on a slow bake",
    "Stocked it full of jelly jars",
    "We're in the basement",
    "Let's meet and have a baby now",
    "Pick 'em, hull 'em, put on the steam",
    "Orange popsicles and lemonade",
    "What's that on your head?",
    "On the neon side of town",
    "She knows where the rain goes",
    "Shake it 'til the butter melts",
    "Just sit on the porch and swing",
    "We'll dance in the garden in torn sheets in the rain",
    "You're what?",
    "Getting nothing but static",
    "Our hearts are traveling faster",
    "Hear the hills scrape the sky",
    "Last night I dreamed I had burning hands",
    "Don't shatter the vision",
    "The vortex spits me out",
    "Electric luau",
    "I'm your daytime waitress at the taco tiki hut",
    "Pink lady with a blue smile",
    "It's a pink helicopter",
    "Livin' on the periphery",
];

document.getElementById("textbox").value = lyrics[Math.floor(Math.random() * lyrics.length)];